name: build
on:
  workflow_dispatch:
  push:
    branches: [ retroscaler-4port ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/darthcloud/idf-blueretro:v5.5.0_2024-12-02

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Build with ESP-IDF
      shell: bash
      run: |
        . $IDF_PATH/export.sh
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        rm -fr build
        echo "$(git describe --always --tags --dirty) hw1 gamecube" | cut -c -31 > version.txt
        cat version.txt
        cp configs/hw1/gamecube sdkconfig
        BR_HW=_hw1 BR_SYS=_gamecube idf.py reconfigure build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: retroscaler4port_hw1_gamecube
        path: |
          build/partition_table/partition-table.bin
          build/bootloader/bootloader.bin
          build/ota_data_initial.bin
          build/BlueRetro*.bin
        if-no-files-found: error
